# Generated by Django 5.1.6 on 2025-02-20 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.ForeignKey(blank=True, limit_choices_to={'choice_type': 'gender'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='users_gender', to='utils.choice'),
        ),
    ]
