# Generated by Django 5.1.6 on 2025-02-20 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_gender'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.ForeignKey(blank=True, default='Active', limit_choices_to={'choice_type': 'status'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='users_status', to='utils.choice'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'choice_type': 'user'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to='utils.choice'),
        ),
    ]
