# Generated by Django 5.1.6 on 2025-02-20 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_status_alter_user_user_type'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.ForeignKey(blank=True, limit_choices_to={'choice_type': 'status'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='users_status', to='utils.choice'),
        ),
    ]
