# Generated by Django 5.1.6 on 2025-02-26 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_image'),
        ('utils', '0002_alter_choice_choice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.ForeignKey(blank=True, limit_choices_to={'choice_type': 'designation'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignee_designation', to='utils.choice'),
        ),
    ]
