# Generated by Django 5.1.6 on 2025-02-24 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_name', models.CharField(choices=[('training', 'Training'), ('compliance', 'Compliance'), ('learning', 'Learning')], default='training', max_length=150, unique=True)),
            ],
            options={
                'db_table': 'Course_Categories',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_title', models.CharField(max_length=255)),
                ('mandatory', models.BooleanField(blank=True, default=False, null=True)),
                ('no_of_assignee', models.PositiveIntegerField()),
                ('course_duration', models.DurationField()),
                ('status', models.ForeignKey(limit_choices_to={'choice_type': 'status'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_status', to='utils.choice')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_category', to='course.coursecategory')),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Assignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('grade', models.CharField(max_length=2)),
                ('type', models.ForeignKey(limit_choices_to={'choice_type': 'assignee'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignee_type', to='utils.choice')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignee_user', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignee_course', to='course.course')),
            ],
            options={
                'db_table': 'assignees',
            },
        ),
    ]
