# Generated by Django 5.1.6 on 2025-02-24 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_question_answer_questionoptions'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coursecategory',
            table='course_categories',
        ),
    ]
