# Generated by Django 5.1.6 on 2025-02-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_coursecategory_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='category_name',
            field=models.CharField(choices=[('training', 'Training'), ('compliance', 'Compliance'), ('learning', 'Learning')], max_length=150, unique=True),
        ),
    ]
