# Generated by Django 5.1.6 on 2025-02-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_coursecategory_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='mandatory',
            new_name='is_mandatory',
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
