# Generated by Django 5.1.6 on 2025-02-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_rename_mandatory_course_is_mandatory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='no_of_assignee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
