# Generated by Django 5.1.6 on 2025-02-25 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_rename_description_lesson_lesson_description'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lesson',
            table='lessons',
        ),
    ]
