# Generated by Django 5.1.6 on 2025-02-25 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_lesson_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionoptions',
            unique_together={('question', 'options')},
        ),
    ]
