# Generated by Django 5.1.6 on 2025-02-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_assignee_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media/lessons_media/'),
        ),
    ]
