# Generated by Django 5.1.6 on 2025-02-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_alter_lesson_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoptions',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
