# Generated by Django 5.1.6 on 2025-02-27 04:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_alter_assignee_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_lesson',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='media',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='assignee',
            unique_together={('course', 'user')},
        ),
    ]
