# Generated by Django 5.1.6 on 2025-02-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choice_name', models.CharField(max_length=150)),
                ('choice_type', models.CharField(choices=[('user', 'User'), ('answer', 'Answer'), ('assignee', 'Assignee'), ('status', 'Status'), ('gender', 'Gender')], max_length=255)),
            ],
            options={
                'db_table': 'choices',
                'unique_together': {('choice_name', 'choice_type')},
            },
        ),
    ]
